name: 06-context
on:
  push:
  workflow_dispatch:
env:
  MY_VAR: Hello world

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Informations
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo: "Event ref: ${{ github.event.ref }}"

          echo "Event sha: ${{ github.event.after }}"
          echo "Event workflow: ${{ github.workflow }}"
          echo "Event action: ${{ github.action }}"
          echo "Event actor: ${{ github.actor }}"
          echo "Event repository: ${{ github.repository }}"
      - name: Retrieve Variables
        run: |
          echo "$MY_VAR"
    