name: Execution flow
on:
  workflow_dispatch: 
    inputs:
      pass-unit-tests:
        description: 'Pass unit tests before proceeding'
        default: false
        type: boolean
jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: lint and build
        run: |
          echo "Linting and building project"
  unit-tests:
    runs-on: ubuntu-latest 
    steps:
      - name: running unit tests
        run: |
          echo "Running tests ..."
      - name: Falling tests
        if: ${{ github.event.inputs.pass-unit-tests == 'false' }}
        run: |
          echo "Tests failed"
          exit 1
  deploy-nonprod:
    runs-on: ubuntu-latest
    needs: [lint-build, unit-tests]
    steps:
      - name: Deploy to non-prod
        run: |
          echo "Deploying to non-prod"

  e2e-tests:
    runs-on: ubuntu-latest
    if: ${{success()}}
    needs: [deploy-nonprod]
    steps:
      - name: Running E2E tests
        run: |
          echo "Running E2E tests"

  load-tests:
    runs-on: ubuntu-latest
    if: ${{success()}}
    needs: [deploy-nonprod]
    steps:
      - name: Running load tests
        run: |
          echo "Running load tests"

  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{success()}}
    needs: [e2e-tests, load-tests]
    steps:
      - name: Deploy to prod
        run: |
          echo "Deploying to prod..."
      