name: 05-filters-activ-types
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: show-triggers
        run: |
          echo "the workflow was triggered by a ${GITHUB_EVENT_NAME} event"
          echo "the workflow was triggered by a ${GITHUB_EVENT_ACTION} action"
          echo "the workflow was triggered by a ${GITHUB_REF} ref"
          echo "the workflow was triggered by a ${GITHUB_SHA} sha"
          echo "the workflow was triggered by a ${GITHUB_WORKFLOW} workflow"