name: 03-workflows-runners
on:
  push:
  
jobs:
  ubuntu-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "Hello world from ${RUNNER_OS} on ${RUNNER_ARCHITECTURE}"
          echo "This is a ${GITHUB_JOB_NAME} job"
          echo "runner OS: $RUNNER_OS}"
  